#服务器端口
server:
  port: 9900

#定义数据库
spring:
  datasource:
    username: root
    password: 2657944563
#    password: root
#    url: jdbc:mysql://10.0.16.13:3306/wzn
    url: jdbc:mysql://124.221.121.147:3306/wzn
#    url: jdbc:mysql://localhost:3306/wzn
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 124.221.121.147
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms



mybatis-plus:
  mapper-locations: classpath:Mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
